print("Nama     : Nanda Eka Rostania")
print("NIM      : 04119020")
print("Prodi    : Sistem Komputer")
print("Fakultas : Ilmu Komputer")
print("Kampus   : Universitas Narotama")
print("Kota     : Surabaya")